class Config:
    # DEFAULTS
    DEFAULT_BOARD_DIMENSION = 10
    DEFAULT_BOMB_PERCENTAGE = 15
    DEFAULT_AI_RADIUS = 3
    DEFAULT_TRAININGSDATA_AMOUNT = 10000
    DEFAULT_AI_TRAININGSDATA_AMOUNT = 10000
    DEFAULT_INCLUDE_BOMB_COUNT = False
    DEFAULT_INCLUDE_HIDDEN_COUNT = False
    DEFAULT_INCLUDE_REVEALED_COUNT = False

    # AI TRAINING
    ONE_HOT_ENCODING = True
    TRAIN_TEST_SPLIT_TEST_SIZE = 0.2
    TRAIN_TEST_SPLIT_RANDOM_STATE = 42
    TRAIN_TEST_SPLIT_SHUFFLE = True
    LOGREG_RANDOM_STATE = 42
    LOGREG_CLASS_WEIGHT = "balanced"
    LOGREG_MAX_ITER = 1000
    TRAINING_SAFE_CELLS = 6
    TRAINING_BOMB_PERCENTAGE_STD_DIVISOR = 6
    TRAINING_MIN_REVEALED_RATIO = 0.25
    BOARD_DIMENSION_PADDING = 5

    # PREDICTION POST-PROCESSING
    PREDICTION_SCALE_MAX = 100
    PREDICTION_UNCERTAINTY_WEIGHT = 0.3
    PREDICTION_UNCERTAINTY_CENTER = 0.5
    CONSIDER_UNKNOWNS = False
    NIEGHBORHOOD_RELEVANT = 1

    # STATS
    CSV_NAME = "data.csv"

config = Config