from global_config import global_config

class Config:
    # DEFAULTS
    DEFAULT_BOARD_DIMENSION = global_config.BOARD_SIZE
    DEFAULT_BOMB_PERCENTAGE = global_config.BOMB_PERCENTAGE
    DEFAULT_AI_RADIUS = 3
    DEFAULT_TRAININGSDATA_AMOUNT = 50000
    DEFAULT_AI_TRAININGSDATA_AMOUNT = 50000
    DEFAULT_INCLUDE_BOMB_COUNT = True
    DEFAULT_INCLUDE_HIDDEN_COUNT = True
    DEFAULT_INCLUDE_REVEALED_COUNT = True

    # AI TRAININ
    ONE_HOT_ENCODING = True
    TRAIN_TEST_SPLIT_TEST_SIZE = 0.1
    TRAIN_TEST_SPLIT_RANDOM_STATE = 42
    TRAIN_TEST_SPLIT_SHUFFLE = True
    LOGREG_RANDOM_STATE = 42
    LOGREG_CLASS_WEIGHT = "balanced"
    LOGREG_MAX_ITER = 2000
    TRAINING_SAFE_CELLS = 8
    TRAINING_BOMB_PERCENTAGE_STD_DIVISOR = 8
    TRAINING_MIN_REVEALED_RATIO = 0.15
    BOARD_DIMENSION_PADDING = 5
    TRAININGSDATA_ALGO_REVEAL = False
    PERCENTAGE_ALGO_REVEAL = 0.5

    # PREDICTION POST-PROCESSING
    PREDICTION_SCALE_MAX = 100
    PREDICTION_UNCERTAINTY_WEIGHT = 0.4
    PREDICTION_UNCERTAINTY_CENTER = 0.5
    CONSIDER_UNKNOWNS = True
    NIEGHBORHOOD_RELEVANT = 2
    VERIFY_FLAG_PLACEMENT = True

    # STATS
    CSV_NAME = "data.csv"

config = Config